# Generated by Django 3.2.16 on 2022-12-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='photo',
            field=models.ImageField(default='Principal/static/img/default_image_project.png', upload_to='Principal/static/img', verbose_name=''),
        ),
    ]
