# Generated by Django 4.1 on 2022-12-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
