# Generated by Django 3.2.16 on 2022-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_proyecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
