# Generated by Django 3.2.16 on 2022-12-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_alter_proyecto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='photo',
            field=models.ImageField(default='Principal/static/img/default_image_project.png', help_text=None, upload_to='Principal/static/img/'),
        ),
    ]
