# Generated by Django 4.1 on 2022-11-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_alter_usuario_last_login_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='Ultima_Conexion', null=True, verbose_name='last login'),
        ),
    ]
