# Generated by Django 4.1 on 2022-11-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_alter_usuario_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='Contraseña', max_length=128, verbose_name='password'),
        ),
    ]
