# Generated by Django 3.2.16 on 2022-12-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0005_auto_20221210_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(default='userImageDefault.png', max_length=40, upload_to='media/ImagePerfil/', verbose_name=''),
        ),
    ]
