# Generated by Django 3.2.16 on 2022-12-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0006_alter_usuario_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Descripcion',
            field=models.TextField(max_length=75),
        ),
        migrations.CreateModel(
            name='LogoTipos',
            fields=[
                ('idLogo', models.AutoField(primary_key=True, serialize=False)),
                ('Logo', models.ImageField(help_text=None, upload_to='media/Logotipos')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.proyecto')),
            ],
        ),
    ]
