# Generated by Django 3.2.16 on 2022-12-13 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0007_auto_20221213_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False)),
                ('Fonts', models.CharField(max_length=100)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='PaletaColores',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False)),
                ('Color', models.CharField(max_length=35)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False)),
                ('Tarea', models.CharField(max_length=100)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.proyecto')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
