# Generated by Django 3.2.16 on 2022-12-13 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0008_auto_20221213_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='photo',
            field=models.ImageField(help_text=None, upload_to='media/ImageProyectos'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='Plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.plan'),
        ),
    ]
