# Generated by Django 3.2.16 on 2022-12-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0009_auto_20221213_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='Fecha_termino',
            field=models.DateTimeField(blank='0000-00-00'),
        ),
    ]
