# Generated by Django 3.2.16 on 2022-12-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0011_alter_suscripcion_fecha_termino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fonts',
            old_name='idTarea',
            new_name='idFont',
        ),
        migrations.RenameField(
            model_name='paletacolores',
            old_name='idTarea',
            new_name='idPaleta',
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='Fecha_termino',
            field=models.DateTimeField(null=True),
        ),
    ]
